server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


    url: jdbc:mysql://121.36.74.25:3306/YiXuanKe?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


  mail:
  #    protocol: smtps
    protocol: smtp
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 2954383503@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: felvhbwvzzesdchi
    # 端口号465或587
    #    port: 465
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8


mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

